<a href="https://colab.research.google.com/github/GrzegorzPiedel/learn_python/blob/master/DS_nauka.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

---

### Spis treści

1. [Podstawy](#a1)
    *   [1D ARRAY](#a1.1)
    * [2D ARRAY](#a1.2)
    * [3D ARRAY](#a1.3)
2. [Typy danych](#a2)
3. [Tworzenie tablic (arange, full, zeros, reshape, linspace)](#a3)
4. [Operacje na tablicach](#a4)







### <a name='a1'></a> Podstawy

In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
help(np.array)

#### <a name='a1.1'></a> 1D ARRAY

In [ ]:
x = np.array((1, 3))
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array((1.4, 1.6, 5.5))
print(x)

[1.4 1.6 5.5]


In [ ]:
x.dtype

dtype('float64')

#### <a name='a1.2'></a> 2D ARRAY

In [ ]:
x = np.array(((1, 2), (-3,2)))
x

array([[ 1,  2],
       [-3,  2]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array(
    ((1, 2, 4),
     (4, 2, 1))
    )
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

#### <a name='a1.3'></a> 3D ARRAY

In [14]:
x =  np.array(
    (((1, 2, 4),
      (4, 2 ,1)),

      ((3, 2, 3),
      (4, 5, 2)))
)
x

array([[[1, 2, 4],
        [4, 2, 1]],

       [[3, 2, 3],
        [4, 5, 2]]])

In [15]:
x.ndim

3

In [16]:
x.shape

(2, 2, 3)

### <a name='a2'></a> Typy danych

In [19]:
A = np.array((1, 3, 2))
A.dtype

dtype('int64')

In [22]:
A = np.array((1.0, 3, 2))
A.dtype

dtype('float64')

In [24]:
A = np.array((1, 3, 2), dtype='float')
A.dtype

dtype('float64')

In [31]:
A = np.array((1.0, 3.4, 2.6), dtype='int')
print(A)
print(A.dtype)

[1 3 2]
int64


In [32]:
A = np.array((True, False))
A.dtype

dtype('bool')

## <a name='a3'></a> Tworzenie tablic

In [34]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [38]:
np.zeros(shape=(2, 4, 10))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [39]:
np.zeros(shape=(2, 3, 4, 10))

array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0.,

In [40]:
np.full(shape=(4, 3), fill_value=7, dtype='int')

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [41]:
np.arange(3)

array([0, 1, 2])

In [42]:
np.arange(6, 12)

array([ 6,  7,  8,  9, 10, 11])

In [43]:
np.arange(0, 12, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5])

In [45]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
np.linspace(3, 100, 10)

array([  3.        ,  13.77777778,  24.55555556,  35.33333333,
        46.11111111,  56.88888889,  67.66666667,  78.44444444,
        89.22222222, 100.        ])

In [49]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
A.reshape(5, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [51]:
A.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## <a name='a4'></a> Operacje na tablicach

In [59]:
A = np.array(((4, 2), (-1, -3)))
B = np.array(((-10, 2), (17, 3)))
print(A, "\n")
print(B)

[[ 4  2]
 [-1 -3]] 

[[-10   2]
 [ 17   3]]


In [60]:
A - B

array([[ 14,   0],
       [-18,  -6]])

In [61]:
A + B

array([[-6,  4],
       [16,  0]])

In [62]:
A * B

array([[-40,   4],
       [-17,  -9]])

In [63]:
A / B

array([[-0.4       ,  1.        ],
       [-0.05882353, -1.        ]])

In [65]:
A + 3

array([[7, 5],
       [2, 0]])

In [66]:
A + 3*B

array([[-26,   8],
       [ 50,   6]])

In [67]:
X = np.array(((7, 4), (-1, -3)))
Y = np.array(((-2, 2), (9, 0)))
print(X, "\n")
print(Y)

[[ 7  4]
 [-1 -3]] 

[[-2  2]
 [ 9  0]]


In [68]:
X * Y

array([[-14,   8],
       [ -9,   0]])

In [69]:
np.dot(X, Y)

array([[ 22,  14],
       [-25,  -2]])

In [70]:
np.dot(Y, X)

array([[-16, -14],
       [ 63,  36]])