<a href="https://colab.research.google.com/github/GrzegorzPiedel/learn_python/blob/master/DataScience_Python/Numpy_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

---

### Spis treści

1. [Podstawy](#a1)
    *   [1D ARRAY](#a1.1)
    * [2D ARRAY](#a1.2)
    * [3D ARRAY](#a1.3)
2. [Typy danych](#a2)
3. [Tworzenie tablic (arange, full, zeros, reshape, linspace)](#a3)
4. [Operacje na tablicach (*+-/, dot, @)](#a4)
5. [Generowanie liczb pseudolosowych (np.random.rand, np.random.randn, np.random.randint, np.random.choice, np.random.shuffle)](#a5)
6. [Podstawowe funkcje (np.exp, np.sqrt, np.any, np.all)](#a6)
7. [Indeksowanie i wycinanie tablic (np.argmin, np.argmax, np.argsort)](#a7)
    *   [Wycinanie](#a7.1)
8. [Iteracja po tablicach (np.flat)](#a8)
9. [Zmiana rozmiaru tablic (np.ravel, np.flatten, .T)](#a9)
10. [Maski logiczne (np.bitwise_and)](#a10)




### <a name='a1'></a> Podstawy

In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
help(np.array)

#### <a name='a1.1'></a> 1D ARRAY

In [ ]:
x = np.array((1, 3))
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array((1.4, 1.6, 5.5))
print(x)

[1.4 1.6 5.5]


In [ ]:
x.dtype

dtype('float64')

#### <a name='a1.2'></a> 2D ARRAY

In [ ]:
x = np.array(((1, 2), (-3,2)))
x

array([[ 1,  2],
       [-3,  2]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array(
    ((1, 2, 4),
     (4, 2, 1))
    )
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

#### <a name='a1.3'></a> 3D ARRAY

In [ ]:
x =  np.array(
    (((1, 2, 4),
      (4, 2 ,1)),

      ((3, 2, 3),
      (4, 5, 2)))
)
x

array([[[1, 2, 4],
        [4, 2, 1]],

       [[3, 2, 3],
        [4, 5, 2]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

### <a name='a2'></a> Typy danych

In [ ]:
A = np.array((1, 3, 2))
A.dtype

dtype('int64')

In [ ]:
A = np.array((1.0, 3, 2))
A.dtype

dtype('float64')

In [ ]:
A = np.array((1, 3, 2), dtype='float')
A.dtype

dtype('float64')

In [ ]:
A = np.array((1.0, 3.4, 2.6), dtype='int')
print(A)
print(A.dtype)

[1 3 2]
int64


In [ ]:
A = np.array((True, False))
A.dtype

dtype('bool')

## <a name='a3'></a> Tworzenie tablic

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.zeros(shape=(2, 4, 10))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [ ]:
np.zeros(shape=(2, 3, 4, 10))

array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0.,

In [ ]:
np.full(shape=(4, 3), fill_value=7, dtype='int')

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
np.arange(6, 12)

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(0, 12, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5])

In [ ]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.linspace(3, 100, 10)

array([  3.        ,  13.77777778,  24.55555556,  35.33333333,
        46.11111111,  56.88888889,  67.66666667,  78.44444444,
        89.22222222, 100.        ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape(5, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## <a name='a4'></a> Operacje na tablicach

In [ ]:
A = np.array(((4, 2), (-1, -3)))
B = np.array(((-10, 2), (17, 3)))
print(A, "\n")
print(B)

[[ 4  2]
 [-1 -3]] 

[[-10   2]
 [ 17   3]]


In [ ]:
A - B

array([[ 14,   0],
       [-18,  -6]])

In [ ]:
A + B

array([[-6,  4],
       [16,  0]])

In [ ]:
A * B

array([[-40,   4],
       [-17,  -9]])

In [ ]:
A / B

array([[-0.4       ,  1.        ],
       [-0.05882353, -1.        ]])

In [ ]:
A + 3

array([[7, 5],
       [2, 0]])

In [ ]:
A + 3*B

array([[-26,   8],
       [ 50,   6]])

In [ ]:
X = np.array(((7, 4), (-1, -3)))
Y = np.array(((-2, 2), (9, 0)))
print(X, "\n")
print(Y)

[[ 7  4]
 [-1 -3]] 

[[-2  2]
 [ 9  0]]


In [ ]:
X * Y

array([[-14,   8],
       [ -9,   0]])

In [ ]:
np.dot(X, Y)

array([[ 22,  14],
       [-25,  -2]])

In [ ]:
np.dot(Y, X)

array([[-16, -14],
       [ 63,  36]])

In [ ]:
X @ Y

array([[ 22,  14],
       [-25,  -2]])

## <a name='a5'></a> Generowanie liczb pseudolosowych

In [ ]:
np.random.randn(4)

array([ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ])

In [ ]:
np.random.randn(5, 2)

array([[-0.97727788,  0.95008842],
       [-0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357],
       [ 1.45427351,  0.76103773],
       [ 0.12167502,  0.44386323]])

In [ ]:
np.random.rand(7)

array([0.94466892, 0.52184832, 0.41466194, 0.26455561, 0.77423369,
       0.45615033, 0.56843395])

In [ ]:
np.random.rand(3, 4)

array([[0.0187898 , 0.6176355 , 0.61209572, 0.616934  ],
       [0.94374808, 0.6818203 , 0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547, 0.66676672, 0.67063787]])

In [ ]:
np.random.randint(18)

0

In [ ]:
np.random.randint(low=31, high=235)

173

In [ ]:
np.random.randint(low=31, high=235, size=9)

array([130,  84, 171, 152, 201, 115, 234,  99,  37])

In [ ]:
np.random.randint(low=31, high=235, size=(5, 5))

array([[227,  78, 158, 162, 131],
       [211, 109, 174, 179, 217],
       [ 54, 172, 148, 116,  79],
       [ 80, 100, 200, 194, 223],
       [126, 228, 125,  31, 144]])

In [ ]:
np.random.choice([3, 5, 6])

6

In [ ]:
np.random.choice(['ala', 'ma', 'kota'])

'kota'

In [ ]:
data = np.arange(15)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.random.shuffle(data)
data

array([ 8, 14, 11, 12,  3,  2,  9,  0, 10,  6,  7,  4, 13,  5,  1])

## <a name='a6'></a> Podstawowe funkcje w NumPy

In [4]:
import numpy as np
np.exp(2)

7.38905609893065

In [5]:
np.sqrt(81)

9.0

In [9]:
np.all([0, 2, 3])

False

In [12]:
np.all([1, True, 3])

True

In [13]:
np.all([1, True, 3, False, 2])

False

In [17]:
np.any([0, 2])

True

In [19]:
np.any([0, 0, 0, 0, 1, 2, 0])

True

In [20]:
np.any([0, 0, 0, 0, False, 2, 0])

True

In [21]:
np.any([0, 0, 0, 0, False, 0, 0])

False

## <a name='a7'></a> Indeksowanie i wycinanie tablic

In [25]:
A = np.random.rand(8)
A

array([0.25953283, 0.81787196, 0.26679151, 0.51579275, 0.654063  ,
       0.73204048, 0.99694822, 0.62299215])

In [27]:
np.argmax(A)

6

In [28]:
A[np.argmax(A)]

0.9969482165170221

In [29]:
np.argmin(A)

0

In [30]:
A[np.argmin(A)]

0.25953282928119115

In [33]:
A = np.random.rand(8)
A

array([0.57665448, 0.13945881, 0.78902008, 0.95646168, 0.22797008,
       0.37688937, 0.68995736, 0.23011071])

In [34]:
np.argsort(A)

array([1, 4, 7, 5, 0, 6, 2, 3])

In [36]:
print(np.min(A))
print(np.max(A))
print(np.std(A))
print(np.median(A))

0.1394588058417141
0.9564616758302215
0.2796903544915404
0.47677192330293755


#### <a name='a7.1'></a> Wycinanie

In [27]:
import numpy as np
A = np.arange(5, 26)
A

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25])

In [28]:
A[3]

8

In [29]:
A[4:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [30]:
A[:5]

array([5, 6, 7, 8, 9])

In [31]:
A = A.reshape(3, 7)
A

array([[ 5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25]])

In [32]:
A[2, 0]

19

In [33]:
A[:2, 1:]

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18]])

In [34]:
A[1, 6] = 88
A

array([[ 5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 88],
       [19, 20, 21, 22, 23, 24, 25]])

## <a name='a8'></a> Iteracja po tablicach

In [35]:
for row in A:
  print(row)

[ 5  6  7  8  9 10 11]
[12 13 14 15 16 17 88]
[19 20 21 22 23 24 25]


In [36]:
for row in A:
  print(row[5])

10
17
24


In [37]:
for item in A.flat:
  print(item)

5
6
7
8
9
10
11
12
13
14
15
16
17
88
19
20
21
22
23
24
25


## <a name='a9'></a> Zmiana rozmiaru tablic

In [38]:
A.ravel()

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 88, 19, 20, 21,
       22, 23, 24, 25])

In [39]:
A

array([[ 5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 88],
       [19, 20, 21, 22, 23, 24, 25]])

In [41]:
A.flatten()[0] = 100
A

array([[ 5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 88],
       [19, 20, 21, 22, 23, 24, 25]])

In [42]:
A.ravel()[0] = 100
A

array([[100,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  88],
       [ 19,  20,  21,  22,  23,  24,  25]])

In [43]:
A.T

array([[100,  12,  19],
       [  6,  13,  20],
       [  7,  14,  21],
       [  8,  15,  22],
       [  9,  16,  23],
       [ 10,  17,  24],
       [ 11,  88,  25]])

## <a name='a10'></a> Maski logiczne

In [45]:
A = np.arange(start=-10, stop=10, step=0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [57]:
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [60]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [61]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [62]:
A[A>-5 and A<5]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [63]:
np.bitwise_and(A>-5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [64]:
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])